// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oloidgdznqksxplqidrv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9sb2lkZ2R6bnFrc3hwbHFpZHJ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzY4NTczMzUsImV4cCI6MjA5MjQzMzMzNX0.4KSit6xywRLCnTPw16H1xTz5mCb0PrBGmOkv-oArQjg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});